### PR TITLE
feat: Validate inputs that cannot be used together

### PR DESCRIPTION
**Pull request by M1kep**

### CODE REVIEW

**Comment by dawidd6** [comment]
Could you please explain how this code exactly works? Frankly I'm not really a JS expert and reading this gives me head scratching.

**Comment by dawidd6** [comment]
Could you please explain how this code exactly works? Frankly I'm not really a JS expert and reading this gives me head scratching.

**Comment by M1kep** [comment]
I've provided an explanation below, let me know if there's still any confusion. I'll also add a different version that may be easier to understand, which I can use instead:

```js
        uniqueInputSets.forEach((inputSet) => {
            /**
             * Given example object of:
             * const example = {
             *     "key1": "value1",
             *     "key2": "value2"
             * }
             *
             * Object.values(example) returns ["value1", "value2"]
             * Object.keys(example) returns ["key1", "key2"]
             *
             * (For each uniqueInputSet)
             * Get the values
             *      Guaranteed to be either the user input or '' (https://github.com/actions/toolkit/blob/c4ae214c261c0d684c6bcfe6632b773b82482bad/packages/core/src/core.ts#L130)
             *
             * These values are passed to the reduce method which takes a reducer(callback) and a starting value
             *      *Official Reduce Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
             * The reducer is called for each item in the array with the below inputs
             *      previousValue(Named occurrences in this case)
             *          This value is the value that was returned by the callback the last time it was called
             *          If it's the first item in the array, the then starting value is used(In this case 0)
             *      currentValue(Named val in this case)
             *          This is the value of the current element in the array
             *
             * The reducer below checks if the user provided input by checking if the value is not ''
             *      If the input was provided by a user, then we increment and return the occurrences variable
             *      which will then be passed into the callback for the next item in the array
             *
             */
            const occurrences = Object.values(inputSet).reduce((occurrences, val) => {
                if (val !== '') {
                    return occurrences++
                }
            },0)
            if(occurrences > 1) {
                throw new Error(`The following inputs cannot be used together: ${Object.keys(inputSet).join(", ")}`)
            }
        })
```

Alternate version which is probably the better option:
```js
        uniqueInputSets.forEach((inputSet) => {
            const inputs = Object.values(inputSet)
            const providedInputs = inputs.filter(input => input !== '')
            if (providedInputs.length > 1) {
                throw new Error(`The following inputs cannot be used together: ${Object.keys(inputSet).join(", ")}`)
            }
        })
```

**Comment by dawidd6** [comment]
Much nicer, thanks. Yet I'm not sure about the second object. Workflow conclusion input has a default value set in action metadata yaml and it does not really collide with run ID, it is just not evaluated when run ID is provided.

**Comment by M1kep** [comment]
Would it be worth updating the ReadMe to remove this limitation then?

- https://github.com/dawidd6/action-download-artifact/blob/80fcec8114889f74eb442780f3c71bff4d42a98a/README.md?plain=1#L11

**Comment by M1kep** [comment]
I've removed the second block

**Comment by dawidd6** [comment]
Thanks

**Pull request merged**
