### PR TITLE
Add pagination to appropriate listWorkflowRunArtifacts call

### PR DESCRIPTION
**Pull request by robbie-unlikelyai**
I have to admit, I'm not really familiar with any of this code - I copied this from a bit further down the file as it seemed to do what was needed. I'm also not really sure what testing needs to be done etc.

More detail is in the issue https://github.com/dawidd6/action-download-artifact/issues/204

### CODE REVIEW

**Comment by jamesmortensen** [comment]
Hi @robbie-unlikelyai it looks like adding pagination has broken some workflows.  We're getting `Cannot read properties of undefined (reading 'artifacts')`.  From what I can tell, the code _looks_ like it should work, but it seems to be returning undefined.  Were you able to see it working on your end?  There's an issue open here:  https://github.com/dawidd6/action-download-artifact/issues/207.

We just downgraded to 2.24.0 and reran our workflow manually for now.

**Comment by robbie-unlikelyai** [comment]
Hey @jamesmortensen - ah that's annoying, sorry! I'm relatively new to GH actions and so hadn't actually tested this end-to-end when I raised the PR. To be honest, I wasn't sure how - I mostly raised this PR as a starting point because I thought the code looked like it _should_ work.

@dawidd6 - perhaps this code should be reverted and a new release made to fix the fact things are broken. We could then have another go at getting this fix in without the bug?

**Comment by dawidd6** [comment]
Reverted for now.

We can have another go, yep.

**Comment by jamesmortensen** [comment]
@robbie-unlikelyai to test it, you could create a workflow that uploads multiple artifacts greater than 30, and then run a workflow immediately after that to call the action-download-artifact.

In .github/workflows you can see some examples of some tests that are there so far.

**Comment by robbie-unlikelyai** [comment]
Thanks @jamesmortensen - a new attempt at this is now in place at https://github.com/dawidd6/action-download-artifact/pull/225. Sorry it's taken so long!

**Pull request merged**
