### PR TITLE
Enable multiple artifact download & artifact name via regex

### PR DESCRIPTION
**Pull request by joseph-flinn**
## Summary

First off, I have found this Action very useful! Thanks for creating it!

For workflows that need multiple artifacts from another workflow, but not all, I'd like the ability to specify specifically which ones to get to avoid downloading more than I need. This change enables that.

### CODE REVIEW

**Comment by dawidd6** [comment]
Why not just running the Action a few times more to get each artifact separately?

**Comment by joseph-flinn** [comment]
One of the workflows that I'm working in requires 6 artifacts. This is a lot of copy/paste which is anti-DRY. Since this Action has the ability to download a single artifact as well as all of the artifacts, I didn't think that adding a filter for some artifacts would change the philosophy of this project.

**Comment by dawidd6** [comment]
Okay, can you modify your changes to also resolve this issue?:
https://github.com/dawidd6/action-download-artifact/issues/85

Supporting regex as name would also enable multiple names as you want.

**Comment by joseph-flinn** [comment]
Sure. The regex functionality has been added.

**Comment by bboles** [comment]
Hi @dawidd6, is there something else holding up this PR from being merged?

**Comment by joseph-flinn** [comment]
I tried resolving the conflicts that have popped up over the last year, but have lost the context to working on this action and don't quite have the capacity to spin back up it.

There's a "fork" over [here](https://github.com/bitwarden/gh-actions/tree/master/download-artifacts) that adds this functionality. That being said, it is provided as-is as there isn't enough capacity on my team to support additional features than what my team needs.

**Comment by dawidd6** [comment]
Closing for now, because of the conflicts. If someone wants to take over the work and push it forward, please open a new PR.

**Pull request closed without merging**
