### PR TITLE
Search capability

### PR DESCRIPTION
**Pull request by martcus**
For those who need to find a certain artifact knowing only its name.

### CODE REVIEW

**Comment by martcus** [comment]
my apologies, now all checks have passed

**Comment by fs24-chrter** [comment]
That's a nice addition 👍

**Comment by Schuchie** [comment]
This is the missing changes, which would help me significantly! Thx for sharing! :)

**Comment by dawidd6** [comment]
It's literally the same functionality as `check_artifacts`.

https://github.com/dawidd6/action-download-artifact/pull/88

**Comment by Schuchie** [comment]
@dawidd6 check_artifacts did not work on my pipeline. It did not found the artifact which was created by an older run.

**Comment by martcus** [comment]
This change allows you to identify and download an artifact based on its name (useful when, for example, you store artifacts with the version name).

from my analysis, the check_artifacts downloads the latest available artifact.

**Comment by dawidd6** [comment]
Change the input to be a boolean, we already have `name` input.

**Comment by martcus** [comment]
Changed. Thanks

**Review by dawidd6 — APPROVED** [review]
Tweaked the logic a bit. Thanks.

**Pull request merged**
