### PR TITLE
download aritfact from latest run which upload an artifact

### PR DESCRIPTION
**Pull request by shitlsh**
Hi, I have the same problem with this issue:#46.
Seeing as words is difficult to elaborate the problem, I try to submit this PR to see if you can understand what we want.
Cause I'm not familiar with the Github Action API, the code change maybe not correct.
There are something I want to explain:
1. I have limited the response `per_page` to `10`, because I find that `asyncFind` will request with each run_id
2. I don't know how to add a auto test to confirm my change

### CODE REVIEW

**Comment by dawidd6** [comment]
I'm gonna wait till this PR is merged: https://github.com/dawidd6/action-download-artifact/pull/90

Then I'll look at this one.

**Comment by dawidd6** [comment]
Solution you provided increases the number of API calls per execution and that number can be high in some cases. I'm not really convinced.

**Comment by shitlsh** [comment]
Yes, you're right.But apparently Github doesn't provide a better way to make it.What if I add a toggle on this feature? 
Something like this
`# Optional, will get the last available artifact from previous workflow, default false, just try to download from the last one
    (can you decide the name):  false

**Comment by dawidd6** [comment]
Yes, a feature flag would be nice. `check_artifacts` maybe? I'm open for suggestions on this one. Also please rebase on latest master as there were changes to this part of code and avoid creating functions, keep it simple.

**Comment by shitlsh** [comment]
Sorry for late reply and thanks for your reminder. I'll set aside some time next week to finish this PR.

**Comment by shitlsh** [comment]
I have fetched upstream and rebased the last changes. I saw you have optimized the loop of `run`, so I followed this change and made my feature more simple.

**Review by dawidd6 — APPROVED** [review]

**Comment by dawidd6** [comment]
Nice. Thanks

**Pull request merged**
