### PR TITLE
Helpful error when lack of source selection

### PR DESCRIPTION
**Pull request by isaacadams**
#52 if no source selections have been configured, then throwing error telling user indicating the issue

### CODE REVIEW

**Comment by dawidd6** [comment]
Thing is that one does not have to specify either runID, branch, pr or commit at all to use this Action.

**Comment by isaacadams** [comment]
this is for #52

**Comment by isaacadams** [comment]
> 
> 
> Thing is that one does not have to specify either runID, branch, pr or commit at all to use this Action.

yet it does not work properly for me when I attempt to use it without specifying one of those parameters. I have since determined the issue to be with collecting the runID through the endpoint when none of them are specified. For some reason it does not work in my workflow context.

**Comment by isaacadams** [comment]
@dawidd6 I think I see the issue. When I set the `branch` input, I used ${{ github.ref }} which would input `refs/heads/<branch-name>` when the code expects only `<branch-name>`

I can create another PR which makes the action capable of processing the former formatting

**Comment by dawidd6** [comment]
Ye, that could be helpful for people I guess. Feel free to PR.

**Pull request closed without merging**
