### PR TITLE
Add input option to unpack (or not) downloaded artifact(s)

### PR DESCRIPTION
**Pull request by daleyjem**
Adds an optional `unpack` input option (`default: true`), so that user can bypass unzipping the downloaded artifacts.

Also... While my first instinct is to `npm i` a Node package, it added quite a bit to `node_modules` and `package-lock.json`, so I reverted that to keep the PR small.

### CODE REVIEW

**Comment by dawidd6** [comment]
Can we have this input inverted? For example rename it to `skip_unpack`, default to false and not use this new function to get boolean value?

**Comment by daleyjem** [comment]
> Can we have this input inverted? For example rename it to `skip_unpack`, default to false and not use this new function to get boolean value?

Like that?

**Comment by daleyjem** [comment]
Lemme see if I can get my tests passing now that workflow filtering seems to be working again, and then I'll take it out of draft

**Comment by daleyjem** [comment]
@dawidd6 Ok... I think it's ready now.

**Comment by dawidd6** [comment]
Thanks

**Pull request merged**
